### ISSUE TITLE
User login screen

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#119]
Screens for Login. This is for the admin tool only. There is no login for the front-end calendar. This issue includes Forgot password, Reset password and a new base layout screen with currently signed in user displayed in the bottom left. This may change in the future but has the basic features.

## Tasks

- [x] https://github.com/culturecreates/footlight-calendar-api/issues/137
- [x] https://github.com/culturecreates/footlight-calendar-api/issues/140
- [x] https://github.com/culturecreates/footlight-calendar-api/issues/135

## Wireframes
![Image](https://user-images.githubusercontent.com/419491/182978777-2fbdaf2a-d5fb-4898-8cb1-38ac045332c5.png)

![Image](https://user-images.githubusercontent.com/419491/183299777-0c8f6aff-9b4d-40d3-8b70-9d9f10c66ec7.png)

![Image](https://user-images.githubusercontent.com/419491/182978308-0e57a209-1002-44b5-b553-561adfb06c4b.png)

![Image](https://user-images.githubusercontent.com/419491/182978303-b5c9fafe-4100-44ce-ab2e-1880af13a2cc.png)

![Image](https://user-images.githubusercontent.com/419491/182978625-e522e1d1-5f88-4d29-b7f8-b960eb52ced0.png)

**Comment by SuhailAliyar** [comment]
@raseemayatt The APIs to reset forgotten password is set.

**Comment by saumier** [comment]
Error messages returned from the API are not displayed:
1. Incorrect OTP error
2. Email not matching an account.
3. Password and confirm password are not the same.

Expected behaviour: The error message returned from the API should be displayed.

**Comment by SuhailAliyar** [comment]
Assigning to @saumier for review.

**Comment by saumier** [comment]
@troughc Please check that messages are displayed when you change the OTP, email and passwords don't match.

**Comment by troughc** [comment]
@saumier results of test:
I did not get an error message when I first enter the wrong OTP code. It seemed like it worked and I was invited to enter a password so I did, and confirmed. Then I got an error message that said that either the OTP or email address were wrong. 

When the passwords don't match, I get the right error message. In other words, that part is okay.

**Comment by saumier** [comment]
@troughc That looks like the correct behaviour. The system only checks if the OTP is correct after the Reset Password button is checked. This is a rare use case, but important to test that the wrong combination gives an error message to the user, without saying if it is the email or OTP.
